// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vqgqcmfaqlfomlnmvrnd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZxZ3FjbWZhcWxmb21sbm12cm5kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2NTI5ODQsImV4cCI6MjA1OTIyODk4NH0.AZHIC1OSw1TpFhHojqyEZJaU-j2qhYoVzku8Gh7FVR8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);